### ISSUE TITLE
Krita Crashes after launch

### ISSUE THREAD

**Issue by theofficialgman** [flathub/org.kde.krita#154]
Opening because of premature closing of: https://github.com/flathub/org.kde.krita/issues/140

`flatpak run org.kde.krita` does not work (crashes after seeing the krita wecome banner)

installed `org.kde.krita.Debug` and the SDK and ran `flatpak run --command=sh --devel org.kde.krita` and obtained a backtrace

```
[📦 org.kde.krita ~]$ gdb /app/bin/krita
GNU gdb (GDB) 12.1
Copyright (C) 2022 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "aarch64-unknown-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /app/bin/krita...
Reading symbols from /usr/lib/debug//app/bin/krita.debug...
(gdb) run
Starting program: /app/bin/krita 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/aarch64-linux-gnu/libthread_db.so.1".
[New Thread 0x7fb005f020 (LWP 12)]
[New Thread 0x7faf7bf020 (LWP 13)]
Qt: Session management error: None of the authentication protocols specified are supported
[Thread 0x7fb005f020 (LWP 12) exited]
[New Thread 0x7fb005f020 (LWP 14)]
Qt: Session management error: None of the authentication protocols specified are supported
[Thread 0x7fb005f020 (LWP 14) exited]
[New Thread 0x7fb005f020 (LWP 15)]
Qt: Session management error: None of the authentication protocols specified are supported
[Thread 0x7fb005f020 (LWP 15) exited]
[New Thread 0x7fb005f020 (LWP 16)]
Gtk-Message: 12:37:11.927: Failed to load module "canberra-gtk-module"
Gtk-Message: 12:37:11.929: Failed to load module "canberra-gtk-module"
Qt: Session management error: None of the authentication protocols specified are supported
[New Thread 0x7f9f16f020 (LWP 17)]
QObject::startTimer: Timers cannot have negative intervals
[New Thread 0x7f9e78b020 (LWP 18)]
[New Thread 0x7f9df7b020 (LWP 19)]
[Thread 0x7f9e78b020 (LWP 18) exited]
/app/lib/krita-python-libs/krita added to PYTHONPATH
[New Thread 0x7f9e78b020 (LWP 20)]

Thread 10 "QQmlThread" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7f9e78b020 (LWP 20)]
0x0000007f9f76ca98 in ?? () from /app/lib/libQt5Qml.so.5
(gdb) backtrace
#0  0x0000007f9f76ca98 in  () at /app/lib/libQt5Qml.so.5
#1  0x0000007f9f76cce4 in  () at /app/lib/libQt5Qml.so.5
#2  0x0000007f9f76a29c in  () at /app/lib/libQt5Qml.so.5
#3  0x0000007f9f76a3fc in  () at /app/lib/libQt5Qml.so.5
#4  0x0000007f9f76a928 in  () at /app/lib/libQt5Qml.so.5
#5  0x0000007f9f864e90 in  () at /app/lib/libQt5Qml.so.5
#6  0x0000007f9f86a5b4 in  () at /app/lib/libQt5Qml.so.5
#7  0x0000007f9f8643f0 in QQmlDataBlob::tryDone() () at /app/lib/libQt5Qml.so.5
#8  0x0000007f9f8659f4 in QQmlTypeLoader::setData(QQmlDataBlob*, QQmlDataBlob::SourceCodeData const&) ()
    at /app/lib/libQt5Qml.so.5
#9  0x0000007f9f866084 in QQmlTypeLoader::setData(QQmlDataBlob*, QString const&) () at /app/lib/libQt5Qml.so.5
#10 0x0000007f9f866274 in QQmlTypeLoader::loadThread(QQmlDataBlob*) () at /app/lib/libQt5Qml.so.5
#11 0x0000007f9f8663d0 in QQmlTypeLoader::load(QQmlDataBlob*, QQmlTypeLoader::Mode) () at /app/lib/libQt5Qml.so.5
#12 0x0000007f9f867350 in QQmlTypeLoader::getType(QUrl const&, QQmlTypeLoader::Mode) () at /app/lib/libQt5Qml.so.5
#13 0x0000007f9f867858 in  () at /app/lib/libQt5Qml.so.5
#14 0x0000007f9f867c0c in  () at /app/lib/libQt5Qml.so.5
#15 0x0000007f9f8659c4 in QQmlTypeLoader::setData(QQmlDataBlob*, QQmlDataBlob::SourceCodeData const&) ()
    at /app/lib/libQt5Qml.so.5
#16 0x0000007f9f866084 in QQmlTypeLoader::setData(QQmlDataBlob*, QString const&) () at /app/lib/libQt5Qml.so.5
#17 0x0000007f9f866274 in QQmlTypeLoader::loadThread(QQmlDataBlob*) () at /app/lib/libQt5Qml.so.5
#18 0x0000007f9f8663d0 in QQmlTypeLoader::load(QQmlDataBlob*, QQmlTypeLoader::Mode) () at /app/lib/libQt5Qml.so.5
#19 0x0000007f9f867350 in QQmlTypeLoader::getType(QUrl const&, QQmlTypeLoader::Mode) () at /app/lib/libQt5Qml.so.5
#20 0x0000007f9f867858 in  () at /app/lib/libQt5Qml.so.5
#21 0x0000007f9f867c0c in  () at /app/lib/libQt5Qml.so.5
#22 0x0000007f9f8659c4 in QQmlTypeLoader::setData(QQmlDataBlob*, QQmlDataBlob::SourceCodeData const&) ()
    at /app/lib/libQt5Qml.so.5
#23 0x0000007f9f866084 in QQmlTypeLoader::setData(QQmlDataBlob*, QString const&) () at /app/lib/libQt5Qml.so.5
#24 0x0000007f9f866274 in QQmlTypeLoader::loadThread(QQmlDataBlob*) () at /app/lib/libQt5Qml.so.5
#25 0x0000007f9f866378 in  () at /app/lib/libQt5Qml.so.5
#26 0x0000007f9f8b1e14 in  () at /app/lib/libQt5Qml.so.5
#27 0x0000007f9f8b2070 in  () at /app/lib/libQt5Qml.so.5
--Type <RET> for more, q to quit, c to continue without paging--RET
#28 0x0000007fb6995c3c in QApplicationPrivate::notify_helper(QObject*, QEvent*) () at /app/lib/libQt5Widgets.so.5
#29 0x0000007fb7cb5310 in KisApplication::notify(QObject*, QEvent*)
     (this=0x7fffffe650, receiver=0x5559302810, event=0x55598bd3f0) at /run/build/krita/libs/ui/KisApplication.cpp:762
#30 0x0000007fb6137270 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /app/lib/libQt5Core.so.5
#31 0x0000007fb6137550 in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) ()
    at /app/lib/libQt5Core.so.5
#32 0x0000007fb61719f0 in  () at /app/lib/libQt5Core.so.5
#33 0x0000007fb1af923c in g_main_context_dispatch () at /usr/lib/aarch64-linux-gnu/libglib-2.0.so.0
#34 0x0000007fb1b4d4b0 in g_main_context_iterate.constprop () at /usr/lib/aarch64-linux-gnu/libglib-2.0.so.0
#35 0x0000007fb1af76d4 in g_main_context_iteration () at /usr/lib/aarch64-linux-gnu/libglib-2.0.so.0
#36 0x0000007fb6171428 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) ()
    at /app/lib/libQt5Core.so.5
#37 0x0000007fb6132ad4 in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /app/lib/libQt5Core.so.5
#38 0x0000007fb5ffd7b8 in QThread::exec() () at /app/lib/libQt5Core.so.5
#39 0x0000007f9f8b17d0 in  () at /app/lib/libQt5Qml.so.5
#40 0x0000007fb5ffec0c in  () at /app/lib/libQt5Core.so.5
#41 0x0000007fb5b8eb98 in start_thread () at /usr/lib/aarch64-linux-gnu/libc.so.6
#42 0x0000007fb5bf779c in thread_start () at /usr/lib/aarch64-linux-gnu/libc.so.6
(gdb)
```

Device info:
```
OS: Ubuntu 18.04.6 LTS
OS architecture: ARM64
Display Server: X11
Kernel: aarch64 4.9.140-l4t
Device model: Nintendo Switch (2017) tegra-x1
Cpu name: Cortex-A57
GPU: NVIDIA Tegra X1 (nvgpu)/integrated
Ram size: 3.99 GB
Language: en_US.UTF-8
```

**Comment by theofficialgman** [comment]
this is a flatpak specific bug
Krita rpm works correctly on Fedora 37 with the same driver stack but does not work with flatpak on either bionic or fedora

**Comment by vulongm** [comment]
I'm not too sure how to reproduce the issue, we're using an older Qt version with Krita's qt patches builds currently similar to the official AppImage builds. Although it will be rebased on a newer version in the next Krita release which may fix it if it is something that the newer build solved. Does the issue also occur in Krita's AppImage build on your device?

**Comment by theofficialgman** [comment]
krita does not produce an official appimage compatible with my device (linux aarch64)

**Comment by vulongm** [comment]
I opened a PR with a build that uses a newer Qt version at #177. Let me know if this issue still occurs there.

**Comment by theofficialgman** [comment]
@vulongm it launches however there is another issue with the krita flatpak (that is not the case in any other flatpak)

you appear to somehow disgard all system flatpak overrides. I have not figured out how you are doing this but all additional permissions that added (like --device=all) are getting removed and not respected in your flatpak

```
flatpak override --show
[Context]
devices=all;
shared=network;
filesystems=/sys;
```
your flatpak removes the override somehow
```
flatpak run --command=sh --devel org.kde.krita
[📦 org.kde.krita ~]$ ls /dev
console  core  fd  full  null  ptmx  pts  random  shm  snd  stderr  stdin  stdout  tty	urandom  zero
```

what I expect the output to be with --device=all set
```
flatpak run --command=sh --devel io.github.arunsivaramanneo.GPUViewer 
[📦 io.github.arunsivaramanneo.GPUViewer ~]$ ls /dev
autofs			gpiochip1     loop3		mmcblk0p4	    nvhost-isp.1      ptyp6	  ram4		  tty0	 tty29	tty49	ttyp1	 vcs
block			gpu_freq_max  loop4		mmcblk0p5	    nvhost-msenc      ptyp7	  ram5		  tty1	 tty3	tty5	ttyp2	 vcs1
btrfs-control		gpu_freq_min  loop5		mmcblk0p6	    nvhost-nvdec      ptyp8	  ram6		  tty10  tty30	tty50	ttyp3	 vcs2
bus			hugepages     loop6		mmcblk0p7	    nvhost-nvjpg      ptyp9	  ram7		  tty11  tty31	tty51	ttyp4	 vcs3
cec0			i2c-0	      loop7		mmcblk0p8	    nvhost-prof-gpu   ptypa	  ram8		  tty12  tty32	tty52	ttyp5	 vcs4
char			i2c-1	      loop-control	mmcblk0p9	    nvhost-sched-gpu  ptypb	  ram9		  tty13  tty33	tty53	ttyp6	 vcs5
console			i2c-101       mapper		mqueue		    nvhost-tsec       ptypc	  random	  tty14  tty34	tty54	ttyp7	 vcs6
constraint_cpu_freq	i2c-2	      max_cpu_power	net		    nvhost-tsecb      ptypd	  rfkill	  tty15  tty35	tty55	ttyp8	 vcsa
constraint_gpu_freq	i2c-3	      max_gpu_power	network_latency     nvhost-tsg-gpu    ptype	  rtc		  tty16  tty36	tty56	ttyp9	 vcsa1
constraint_online_cpus	i2c-4	      max_online_cpus	network_throughput  nvhost-vic	      ptypf	  rtc0		  tty17  tty37	tty57	ttypa	 vcsa2
cpu_dma_latency		i2c-5	      mem		null		    nvmap	      quadd	  rtc1		  tty18  tty38	tty58	ttypb	 vcsa3
cpu_freq_max		iio:device0   memory_bandwidth	nvhdcp1		    port	      quadd_auth  shm		  tty19  tty39	tty59	ttypc	 vcsa4
cpu_freq_min		iio:device1   min_online_cpus	nvhost-as-gpu	    ppp		      ram0	  snd		  tty2	 tty4	tty6	ttypd	 vcsa5
cuse			initctl       mmcblk0		nvhost-ctrl	    psaux	      ram1	  stderr	  tty20  tty40	tty60	ttype	 vcsa6
disk			input	      mmcblk0p1		nvhost-ctrl-gpu     ptmx	      ram10	  stdin		  tty21  tty41	tty61	ttypf	 zero
emc_freq_min		keychord      mmcblk0p10	nvhost-ctrl-isp     pts		      ram11	  stdout	  tty22  tty42	tty62	ttyS0	 zram0
fb0			kmem	      mmcblk0p11	nvhost-ctrl-isp.1   ptyp0	      ram12	  tegra-crypto	  tty23  tty43	tty63	ttyS1
fb1			kmsg	      mmcblk0p12	nvhost-ctrl-nvdec   ptyp1	      ram13	  tegra_dc_0	  tty24  tty44	tty7	ttyS2
fd			log	      mmcblk0p13	nvhost-ctxsw-gpu    ptyp2	      ram14	  tegra_dc_1	  tty25  tty45	tty8	ttyS3
full			loop0	      mmcblk0p14	nvhost-dbg-gpu	    ptyp3	      ram15	  tegra_dc_ctrl   tty26  tty46	tty9	uhid
fuse			loop1	      mmcblk0p2		nvhost-gpu	    ptyp4	      ram2	  tegra_mipi_cal  tty27  tty47	ttyGS0	uinput
gpiochip0		loop2	      mmcblk0p3		nvhost-isp	    ptyp5	      ram3	  tty		  tty28  tty48	ttyp0	urandom
```

**Comment by theofficialgman** [comment]
you can see this with flatpak info as well. your flatpak manages to remove the system overrides that I specified
```
flatpak info --show-permissions org.kde.krita
[Context]
shared=network;ipc;
sockets=x11;pulseaudio;
devices=dri;
filesystems=host;xdg-run/gvfs;

[Session Bus Policy]
com.canonical.AppMenu.Registrar=talk

[System Bus Policy]
org.freedesktop.ColorManager=talk

[Environment]
TMPDIR=/var/tmp
XDG_CURRENT_DESKTOP=gtk3
PYTHONPATH=/app/lib/python3/dist-packages
```

a different flatpak that behaves properly
```
flatpak info --show-permissions io.github.arunsivaramanneo.GPUViewer 
[Context]
shared=network;ipc;
sockets=x11;wayland;
devices=dri;all;
filesystems=/sys;
```

**Comment by theofficialgman** [comment]
ignore the above comments. yes the issue is fixed in the beta package
